#fname=Notes_about_network_propagation
#baname=BachelorThesis
#baname=thesis
#Notes_about_network_propagation.pdf: Notes_about_network_propagation.tex mybib.bib
#	pdflatex $(fname)
#	biber $(fname)
#	pdflatex $(fname)
name = topic_list

topic_list.pdf:
	pdflatex $(name)
	biber $(name)
	pdflatex $(name)
